# Generated by sila2.code_generator; sila2.__version__: 0.10.1
from __future__ import annotations

from typing import TYPE_CHECKING, List

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.labwaretransfersiteurcontroller import (
    HandoverPosition,
    LabwareDelivered_Responses,
    LabwareRemoved_Responses,
    LabwareTransferSiteURControllerBase,
    PositionIndex,
    PrepareForInput_Responses,
    PrepareForOutput_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


class LabwareTransferSiteURControllerImpl(LabwareTransferSiteURControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def get_AvailableHandoverPositions(self, *, metadata: MetadataDict) -> List[HandoverPosition]:
        raise NotImplementedError  # TODO

    def get_NumberOfInternalPositions(self, *, metadata: MetadataDict) -> int:
        raise NotImplementedError  # TODO

    def PrepareForInput(
        self,
        HandoverPosition: HandoverPosition,
        InternalPosition: PositionIndex,
        LabwareType: str,
        LabwareUniqueID: str,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> PrepareForInput_Responses:
        instance.begin_execution()  # set execution status from `waiting` to `running`
        raise NotImplementedError  # TODO

    def PrepareForOutput(
        self,
        HandoverPosition: HandoverPosition,
        InternalPosition: PositionIndex,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> PrepareForOutput_Responses:
        instance.begin_execution()  # set execution status from `waiting` to `running`
        raise NotImplementedError  # TODO

    def LabwareDelivered(
        self, HandoverPosition: HandoverPosition, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> LabwareDelivered_Responses:
        instance.begin_execution()  # set execution status from `waiting` to `running`
        raise NotImplementedError  # TODO

    def LabwareRemoved(
        self, HandoverPosition: HandoverPosition, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> LabwareRemoved_Responses:
        instance.begin_execution()  # set execution status from `waiting` to `running`
        raise NotImplementedError  # TODO
