# Generated by sila2.code_generator; sila2.__version__: 0.7.3

from typing import Optional
from uuid import UUID

from sila2.server import SilaServer
from UR_Server.hardware_interface import PreciseInterface

from .feature_implementations.labwaretransfercontroller_impl import LabwareTransferControllerImpl
from .feature_implementations.robotexample_impl import RobotExampleImpl
from .generated.labwaretransfercontroller import LabwareTransferControllerFeature
from .generated.robotexample import RobotExampleFeature


class Server(SilaServer):
    def __init__(self, server_uuid: Optional[UUID] = None):
        # TODO: fill in your server information
        super().__init__(
            server_name="Precise",
            server_type="TODO",
            server_version="1.0",
            server_description="TODO",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid,
        )
        self.hardware_interface = PreciseInterface()

        self.labwaretransfercontroller = LabwareTransferControllerImpl(self, self.hardware_interface)
        self.robotexample = RobotExampleImpl(self, self.hardware_interface)

        self.set_feature_implementation(LabwareTransferControllerFeature, self.labwaretransfercontroller)
        self.set_feature_implementation(RobotExampleFeature, self.robotexample)
