# Generated by sila2.code_generator; sila2.__version__: 0.10.1
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.connectioncontroller import ConnectionControllerBase, ConnectToRobot_Responses

if TYPE_CHECKING:
    from ..server import Server


class ConnectionControllerImpl(ConnectionControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.run_periodically(
            lambda: self.update_ConnectionStatus(False),
            delay_seconds=1
      )

    def ConnectToRobot(self, *, metadata: MetadataDict) -> ConnectToRobot_Responses:
        self.parent_server.robot_interface.connect()
        return ConnectToRobot_Responses(False)
