# Generated by sila2.code_generator; sila2.__version__: 0.10.1

from typing import Optional
from uuid import UUID

from sila2.server import SilaServer

from .feature_implementations.robotcontroller_impl import RobotControllerImpl
from .generated.robotcontroller import RobotControllerFeature
from .UR_utils.UR_Arm import UR_Robot


class Server(SilaServer):
    def __init__(self, server_uuid: Optional[UUID] = None):
        # TODO: fill in your server information
        super().__init__(
            server_name="UR_Robot",
            server_type="Device",
            server_version="0.1",
            server_description="Implementation of UR Robot Arm",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid,
        )
        self.robotcontroller = RobotControllerImpl(self)
        self.set_feature_implementation(RobotControllerFeature, self.robotcontroller)
