# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handover.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='handover.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ehandover.proto\"\x89\x01\n\x08Handover\x12;\n\x10HandoverPosition\x18\x01 \x03(\x0b\x32!.Handover.HandoverPosition_Struct\x1a@\n\x17HandoverPosition_Struct\x12\x10\n\x08Position\x18\x01 \x01(\t\x12\x13\n\x0bSubPosition\x18\x02 \x01(\x05\x62\x06proto3'
)




_HANDOVER_HANDOVERPOSITION_STRUCT = _descriptor.Descriptor(
  name='HandoverPosition_Struct',
  full_name='Handover.HandoverPosition_Struct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Position', full_name='Handover.HandoverPosition_Struct.Position', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SubPosition', full_name='Handover.HandoverPosition_Struct.SubPosition', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=156,
)

_HANDOVER = _descriptor.Descriptor(
  name='Handover',
  full_name='Handover',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='HandoverPosition', full_name='Handover.HandoverPosition', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_HANDOVER_HANDOVERPOSITION_STRUCT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=156,
)

_HANDOVER_HANDOVERPOSITION_STRUCT.containing_type = _HANDOVER
_HANDOVER.fields_by_name['HandoverPosition'].message_type = _HANDOVER_HANDOVERPOSITION_STRUCT
DESCRIPTOR.message_types_by_name['Handover'] = _HANDOVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Handover = _reflection.GeneratedProtocolMessageType('Handover', (_message.Message,), {

  'HandoverPosition_Struct' : _reflection.GeneratedProtocolMessageType('HandoverPosition_Struct', (_message.Message,), {
    'DESCRIPTOR' : _HANDOVER_HANDOVERPOSITION_STRUCT,
    '__module__' : 'handover_pb2'
    # @@protoc_insertion_point(class_scope:Handover.HandoverPosition_Struct)
    })
  ,
  'DESCRIPTOR' : _HANDOVER,
  '__module__' : 'handover_pb2'
  # @@protoc_insertion_point(class_scope:Handover)
  })
_sym_db.RegisterMessage(Handover)
_sym_db.RegisterMessage(Handover.HandoverPosition_Struct)


# @@protoc_insertion_point(module_scope)
